### ISSUE TITLE
Context menu interacts with incorrect file

### ISSUE THREAD

**Issue by mattpilott** [facebookexperimental/atom-menu-patch-for-catalina#2]
Hello,

I'm sure you are already aware of this, but right clicking a file (say file-a.text) whilst file-b.text is open performs it's actions on the open file the the file that was right clicked.

Are we able to fix this?

**Comment by evangrayk** [comment]
Thanks for reporting this! I can't seem to reproduce this, is this what you're experiencing:
- Open two files, A.txt and B.txt side-by-side
- click on A.txt so the cursor is active there
- right click in B.txt, and do "select all"
- Expected: content of B.txt is selected, Bug: content of A.txt is selected?

Could it be particular menu commands causing this?

**Comment by dbalcomb** [comment]
My experience has been that the rename and duplicate options on files and folders in the tree view do not target the selected file but rather the current active file in the editor or do nothing when there is no file open. The same issue is also mentioned [here](https://github.com/atom/atom/issues/20034#issuecomment-571859782).
