### ISSUE TITLE
Context menu cuts off.

### ISSUE THREAD

**Issue by codenift** [facebookexperimental/atom-menu-patch-for-catalina#4]
The only issue I found now with this extension is the context menu getting cut off, menu will not change direction. Needs a way to detect window height. On the file tree it would work if mouse is position above 110pixels inside Atom but when below it will get cut off. On the edit window, it will get cut off anywhere I positioned the mouse.

Below 110 pixels on file tree:
![Screen Shot 2020-01-09 at 9 54 56 AM](https://user-images.githubusercontent.com/6990593/72079333-b503e200-32c8-11ea-84c5-2257963138e3.png)

So the only way to get around this is by scrolling the file tree so that the file your aiming for stays above that 110pixels, except when the file tree reaches the bottom, then the menu gets cut off again.

On the edit window it's always cutting off:
![Screen Shot 2020-01-09 at 9 57 43 AM](https://user-images.githubusercontent.com/6990593/72079531-1b890000-32c9-11ea-9dc0-860046c6d2eb.png)

Maybe detecting the height of the context menu itself and then calculate the window height in the app, and only show the menu upwards if the height of the menu is going to pass the bottom. The only problem is, when using on my laptop for example, the menu doesn't completely show everything if having a few extensions active since it will show more content on the menu. So i guess, if calculating the size of the context menu, that could be used to also enable a scroll inside the menu if it reaches a 90% of the window in Atom.

**Comment by evangrayk** [comment]
Just put up a semi-hacky fix for this: https://github.com/facebookexperimental/atom-menu-patch-for-catalina/commit/786af3904d13f8d4e4d384f01b7738ab592e4bda

It makes the menu never go above the top of the screen, and lets you scroll if the window is too small. Closing this issue for now, let me know if you experience issues with this fix.

**Comment by codenift** [comment]
I think this is perfect!  Only one small issue though... I can get into the submenus when on the edit window.
