### ISSUE TITLE
Electron 5.0.12 hit the stable branch in Atom

### ISSUE THREAD

**Issue by michalmiddleton** [facebookexperimental/atom-menu-patch-for-catalina#6]
Hi, it appears that Atom v1.47.0 includes https://github.com/atom/atom/pull/20172 (Electron 5.0.12). Just wanted to say thank you for improving our quality of life for this time period :)

**Comment by evangrayk** [comment]
Awesome, thanks for mentioning! I'll update the README to say this is no longer needed
